# Applying functions in R

Installing to tead Excel files:

In [ ]:
install.packages('rio', repos = "https://cran.rstudio.com/")  # Installs the rio package for reading Excel files

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

# reading data

In [ ]:
# opening a file from a url (file in Excel), name it 'fragility23'
linkGit="https://github.com/FundamentalsChinmai/Hw02/raw/refs/heads/main/FSI-2023-DOWNLOAD.xlsx"  # Store the URL in a variable

# library(rio) # package needed
fragility23=rio::import(file = linkGit)  # Read Excel file from URL (using import function from rio package) and store in fragility23

In [ ]:
str(fragility23)  # Shows the structure: data type, dimensions, and column info

'data.frame':	179 obs. of  16 variables:
 $ Country                         : chr  "Somalia" "Yemen" "South Sudan" "Congo Democratic Republic" ...
 $ Year                            : num  2023 2023 2023 2023 2023 ...
 $ Rank                            : chr  "1st" "2nd" "3rd" "4th" ...
 $ Total                           : num  112 109 109 107 107 ...
 $ S1: Demographic Pressures       : num  10 9.6 9.7 9.7 7.4 9.2 8.8 9.3 9.5 8.8 ...
 $ S2: Refugees and IDPs           : num  9 9.6 10 9.8 9.1 8.6 9.6 9.5 9 7.7 ...
 $ C3: Group Grievance             : num  8.7 8.8 8.6 9.4 9.1 8.3 9.3 8.1 8.1 5.5 ...
 $ E3: Human Flight and Brain Drain: num  8.6 6.4 6.5 6.4 8 8.5 7.5 6.2 7.7 8.3 ...
 $ E2: Economic Inequality         : num  9.1 7.9 8.6 8.4 6.5 8.2 8.5 9.6 8.7 9.2 ...
 $ E1: Economy                     : num  9.5 9.9 8.6 8.1 9.6 9.6 9.3 8.2 8.4 8.9 ...
 $ P1: State Legitimacy            : num  9.6 9.8 9.8 9.3 10 9.4 9.4 8.9 9.1 9.9 ...
 $ P2: Public Services             : num  9.8 9.6 9.7 9.3 9 10 8.6 10 9.6 9.8 ...
 $ P3: Human Rights                : num  9 9.6 8.7 9.3 9.1 8.7 9.2 9.1 8.4 8.7 ...
 $ C1: Security Apparatus          : num  9.5 8.6 9.9 8.8 9.4 9.7 8.3 8 8.7 6.8 ...
 $ C2: Factionalized Elites        : num  10 9.9 9.2 9.6 9.9 8.7 9.6 9.4 9.5 9.7 ...
 $ X1: External Intervention       : num  9.1 9.2 9.2 9.1 10 7.7 8.1 9.4 7.9 9.6 ...

## Apply square root function?

In [ ]:
# whole DF?
# sqrt(fragility23)  # This would error because can't take sqrt of non-numeric columns

In [ ]:
# several columns (only numerical)

sqrt(fragility23[,4:5])  # Calculate square root of all values in columns 4 and 5 ([,4:5] means all rows, cols 4 and 5)

    Total     S1: Demographic Pressures
1   10.578280 3.162278
2   10.435516 3.098387
3   10.416333 3.114482
4   10.353743 3.114482
5   10.348913 2.720294
6   10.324728 3.033150
7   10.305338 2.966479
8   10.281051 3.049590
9   10.227414 3.082207
10  10.143964 2.966479
11  10.019980 3.130495
12  10.009995 2.645751
13   9.974969 2.966479
14   9.924717 2.966479
15   9.899495 3.098387
16   9.843780 2.949576
17   9.803061 2.449490
18   9.792855 2.701851
19   9.721111 2.774887
20   9.705668 2.949576
21   9.695360 2.880972
22   9.695360 3.098387
23   9.695360 3.000000
24   9.664368 2.983287
25   9.581232 2.408319
26   9.565563 3.033150
27   9.560335 2.863564
28   9.523655 2.915476
29   9.513149 2.549510
30   9.502631 2.683282
⋮   ⋮         ⋮
150 6.356099  1.702939
151 6.340347  1.788854
152 6.276942  1.897367
153 6.212890  1.702939
154 6.164414  1.760682
155 6.148170  1.612452
156 6.082763  1.897367
157 5.865151  1.843909
158 5.744563  1.923538
159 5.612486  1.581139
160 5.603570  2.049390
161 5.522681  2.428992
162 5.366563  1.760682
163 5.224940  1.897367
164 5.069517  2.000000
165 5.049752  1.581139
166 4.959839  1.516575
167 4.939636  1.897367
168 4.690416  1.949359
169 4.582576  1.581139
170 4.538722  1.732051
171 4.415880  1.549193
172 4.415880  1.673320
173 4.347413  1.095445
174 4.230839  1.516575
175 4.219005  1.549193
176 4.086563  1.048809
177 4.000000  1.303840
178 3.962323  1.224745
179 3.807887  1.183216

In [ ]:
# one column
sqrt(fragility23$Total)  # Calculate square root of all values in the Total column ($ accesses column by name)

  [1] 10.578280 10.435516 10.416333 10.353743 10.348913 10.324728 10.305338
  [8] 10.281051 10.227414 10.143964 10.019980 10.009995  9.974969  9.924717
 [15]  9.899495  9.843780  9.803061  9.792855  9.721111  9.705668  9.695360
 [22]  9.695360  9.695360  9.664368  9.581232  9.565563  9.560335  9.523655
 [29]  9.513149  9.502631  9.481561  9.481561  9.428680  9.375500  9.370165
 [36]  9.332738  9.327379  9.327379  9.322017  9.241212  9.230385  9.186947
 [43]  9.121403  9.071935  9.066422  9.066422  9.060905  9.044335  9.038805
 [50]  9.033272  9.022195  9.011104  8.983318  8.961027  8.955445  8.921883
 [57]  8.921883  8.893818  8.837420  8.837420  8.820431  8.814760  8.803408
 [64]  8.792042  8.752143  8.734987  8.723531  8.700575  8.694826  8.642916
 [71]  8.631338  8.613942  8.608136  8.561542  8.549854  8.526429  8.502941
 [78]  8.485281  8.479387  8.455767  8.408329  8.378544  8.366600  8.360622
 [85]  8.354639  8.348653  8.330666  8.324662  8.324662  8.258329  8.246211
 [92]  8.240146  8.215838  8.209750  8.173127  8.148620  8.148620  8.099383
 [99]  8.093207  8.080842  8.068457  8.068457  8.068457  8.031189  7.981228
[106]  7.930952  7.893035  7.867655  7.848567  7.797435  7.784600  7.765307
[113]  7.765307  7.752419  7.733046  7.726578  7.713624  7.635444  7.615773
[120]  7.549834  7.536577  7.436397  7.422937  7.416198  7.395945  7.334848
[127]  7.328028  7.300685  7.280110  7.273239  7.197222  7.162402  7.155418
[134]  7.014271  6.985700  6.978539  6.978539  6.978539  6.811755  6.737952
[141]  6.730527  6.723095  6.640783  6.595453  6.580274  6.526868  6.496153
[148]  6.473021  6.363961  6.356099  6.340347  6.276942  6.212890  6.164414
[155]  6.148170  6.082763  5.865151  5.744563  5.612486  5.603570  5.522681
[162]  5.366563  5.224940  5.069517  5.049752  4.959839  4.939636  4.690416
[169]  4.582576  4.538722  4.415880  4.415880  4.347413  4.230839  4.219005
[176]  4.086563  4.000000  3.962323  3.807887

In [ ]:
# one value
sqrt(fragility23$Total[1])  # Calculate square root of just the first value in Total column ([1] means first element)

[1] 10.57828

## Applying **sum()**:

In [ ]:
# sum everything
sum(fragility23[,4:5])  # Add up all values in columns 4 and 5, returns one total number

[1] 12850.1

In [ ]:
# sum by column
print(apply(fragility23[,4:5],2,sum))  # Apply sum to each column (2=columns), returns separate sum for each column

                    Total S1: Demographic Pressures
                  11784.0                    1066.1

In [ ]:
#notice
typeof(apply(fragility23[,4:5],2,sum))  # Check the data type that apply() returns (should be vector, not list)

[1] "double"

If you do not see **list**, then it is a vector. ⏫

In [ ]:
# sum by row
print(apply(fragility23[,4:5],1,sum))  # Apply sum to each row (1=rows), returns one sum per row across columns 4 and 5

    1     2     3     4     5     6     7     8     9    10    11    12    13
121.9 118.5 118.2 116.9 114.5 115.8 115.0 115.0 114.1 111.7 110.2 107.2 108.3
   14    15    16    17    18    19    20    21    22    23    24    25    26
107.3 107.6 105.6 102.1 103.2 102.2 102.9 102.3 103.6 103.0 102.3  97.6 100.7
   27    28    29    30    31    32    33    34    35    36    37    38    39
 99.6  99.2  97.0  97.5  98.8  98.2  97.3  96.2  95.9  95.7  95.6  94.3  96.2
   40    41    42    43    44    45    46    47    48    49    50    51    52
 92.2  92.9  93.5  92.8  89.5  90.4  89.3  89.5  91.2  91.3  88.3  89.8  85.7
   53    54    55    56    57    58    59    60    61    62    63    64    65
 85.5  86.7  88.3  86.7  86.5  87.8  85.9  85.5  85.7  82.7  86.2  84.4  85.2
   66    67    68    69    70    71    72    73    74    75    76    77    78
 84.9  84.3  82.0  81.3  81.1  83.2  81.2  82.6  81.3  80.7  76.5  78.4  80.0
   79    80    81    82    83    84    85    86    87    88    89    90    91
 76.6  78.9  77.6  74.8  75.0  74.7  76.7  76.6  76.1  75.1  76.1  72.6  74.1
   92    93    94    95    96    97    98    99   100   101   102   103   104
 72.0  71.3  72.8  71.1  71.8  70.7  72.6  72.2  69.6  69.8  69.2  71.6  70.1
  105   106   107   108   109   110   111   112   113   114   115   116   117
 69.4  68.1  69.7  66.7  67.4  67.2  64.7  68.4  64.5  66.3  64.8  65.2  65.4
  118   119   120   121   122   123   124   125   126   127   128   129   130
 62.7  62.1  60.4  60.9  63.1  59.2  60.1  57.5  57.5  57.8  57.5  57.5  57.0
  131   132   133   134   135   136   137   138   139   140   141   142   143
 57.2  56.1  55.6  55.5  52.3  53.6  52.9  53.5  52.1  49.1  50.5  49.0  48.9
  144   145   146   147   148   149   150   151   152   153   154   155   156
 46.8  46.5  47.2  48.1  45.3  43.5  43.3  43.4  43.0  41.5  41.1  40.4  40.6
  157   158   159   160   161   162   163   164   165   166   167   168   169
 37.8  36.7  34.0  35.6  36.4  31.9  30.9  29.7  28.0  26.9  28.0  25.8  23.5
  170   171   172   173   174   175   176   177   178   179
 23.6  21.9  22.3  20.1  20.2  20.2  17.8  17.7  17.2  15.9

### Apply by iterating:

In [ ]:
print(lapply(fragility23[,4:5],sum))  # Apply sum to each column, always returns a list (lapply = list apply)

$Total
[1] 11784

$`S1: Demographic Pressures`
[1] 1066.1

Notice output of **lapply**:

In [ ]:
typeof(lapply(fragility23[,4:5],sum))  # Check type: lapply always returns a list

[1] "list"

In [ ]:
class(lapply(fragility23[,4:5],sum))  # Check class: shows R's object category (different from typeof which shows storage type)

[1] "list"

Notice output of **sapply**:

In [ ]:
print(sapply(fragility23[,4:5],sum))  # Apply sum to each column, tries to simplify result (might return vector instead of list)

                    Total S1: Demographic Pressures
                  11784.0                    1066.1

In [ ]:
class(sapply(fragility23[,4:5],sum))  # Check class: sapply simplified to vector/array (simpler than lapply's list)

[1] "numeric"

Similarly:

In [ ]:
print(lapply(fragility23[,4:5],sqrt))  # Apply sqrt to each column, returns list with sqrt of each column

$Total
  [1] 10.578280 10.435516 10.416333 10.353743 10.348913 10.324728 10.305338
  [8] 10.281051 10.227414 10.143964 10.019980 10.009995  9.974969  9.924717
 [15]  9.899495  9.843780  9.803061  9.792855  9.721111  9.705668  9.695360
 [22]  9.695360  9.695360  9.664368  9.581232  9.565563  9.560335  9.523655
 [29]  9.513149  9.502631  9.481561  9.481561  9.428680  9.375500  9.370165
 [36]  9.332738  9.327379  9.327379  9.322017  9.241212  9.230385  9.186947
 [43]  9.121403  9.071935  9.066422  9.066422  9.060905  9.044335  9.038805
 [50]  9.033272  9.022195  9.011104  8.983318  8.961027  8.955445  8.921883
 [57]  8.921883  8.893818  8.837420  8.837420  8.820431  8.814760  8.803408
 [64]  8.792042  8.752143  8.734987  8.723531  8.700575  8.694826  8.642916
 [71]  8.631338  8.613942  8.608136  8.561542  8.549854  8.526429  8.502941
 [78]  8.485281  8.479387  8.455767  8.408329  8.378544  8.366600  8.360622
 [85]  8.354639  8.348653  8.330666  8.324662  8.324662  8.258329  8.246211
 [92]  8.240146  8.215838  8.209750  8.173127  8.148620  8.148620  8.099383
 [99]  8.093207  8.080842  8.068457  8.068457  8.068457  8.031189  7.981228
[106]  7.930952  7.893035  7.867655  7.848567  7.797435  7.784600  7.765307
[113]  7.765307  7.752419  7.733046  7.726578  7.713624  7.635444  7.615773
[120]  7.549834  7.536577  7.436397  7.422937  7.416198  7.395945  7.334848
[127]  7.328028  7.300685  7.280110  7.273239  7.197222  7.162402  7.155418
[134]  7.014271  6.985700  6.978539  6.978539  6.978539  6.811755  6.737952
[141]  6.730527  6.723095  6.640783  6.595453  6.580274  6.526868  6.496153
[148]  6.473021  6.363961  6.356099  6.340347  6.276942  6.212890  6.164414
[155]  6.148170  6.082763  5.865151  5.744563  5.612486  5.603570  5.522681
[162]  5.366563  5.224940  5.069517  5.049752  4.959839  4.939636  4.690416
[169]  4.582576  4.538722  4.415880  4.415880  4.347413  4.230839  4.219005
[176]  4.086563  4.000000  3.962323  3.807887

$`S1: Demographic Pressures`
  [1] 3.162278 3.098387 3.114482 3.114482 2.720294 3.033150 2.966479 3.049590
  [9] 3.082207 2.966479 3.130495 2.645751 2.966479 2.966479 3.098387 2.949576
 [17] 2.449490 2.701851 2.774887 2.949576 2.880972 3.098387 3.000000 2.983287
 [25] 2.408319 3.033150 2.863564 2.915476 2.549510 2.683282 2.983287 2.880972
 [33] 2.898275 2.880972 2.846050 2.932576 2.932576 2.701851 3.049590 2.607681
 [41] 2.774887 3.016621 3.098387 2.683282 2.863564 2.664583 2.720294 3.065942
 [49] 3.098387 2.588436 2.898275 2.121320 2.190890 2.529822 2.846050 2.664583
 [57] 2.626785 2.949576 2.792848 2.720294 2.810694 2.236068 2.949576 2.664583
 [65] 2.932576 2.932576 2.863564 2.509980 2.387467 2.529822 2.949576 2.645751
 [73] 2.915476 2.828427 2.756810 1.949359 2.469818 2.828427 2.167948 2.720294
 [81] 2.626785 2.144761 2.236068 2.190890 2.626785 2.626785 2.588436 2.408319
 [89] 2.607681 2.097618 2.469818 2.024846 1.949359 2.323790 2.073644 2.323790
 [97] 2.073644 2.645751 2.588436 2.073644 2.167948 2.024846 2.549510 2.366432
[105] 2.387467 2.280351 2.720294 2.190890 2.408319 2.529822 2.024846 2.846050
[113] 2.049390 2.489980 2.236068 2.345208 2.428992 2.097618 2.024846 1.843909
[121] 2.024846 2.792848 2.024846 2.258318 1.673320 1.923538 2.024846 2.049390
[129] 2.121320 2.024846 2.323790 2.190890 2.097618 2.509980 1.870829 2.213594
[137] 2.049390 2.190890 2.387467 1.923538 2.280351 1.949359 2.190890 1.816590
[145] 1.788854 2.144761 2.428992 1.843909 1.732051 1.702939 1.788854 1.897367
[153] 1.702939 1.760682 1.612452 1.897367 1.843909 1.923538 1.581139 2.049390
[161] 2.428992 1.760682 1.897367 2.000000 1.581139 1.516575 1.897367 1.949359
[169] 1.581139 1.732051 1.549193 1.673320 1.095445 1.516575 1.549193 1.048809
[177] 1.303840 1.224745 1.183216

In [ ]:
class(lapply(fragility23[,4:5],sqrt))  # Check class: lapply with sqrt still returns a list

[1] "list"

In [ ]:
print(sapply(fragility23[,4:5],sqrt))  # Apply sqrt to each column, tries to simplify (might return matrix instead of list)

           Total S1: Demographic Pressures
  [1,] 10.578280                  3.162278
  [2,] 10.435516                  3.098387
  [3,] 10.416333                  3.114482
  [4,] 10.353743                  3.114482
  [5,] 10.348913                  2.720294
  [6,] 10.324728                  3.033150
  [7,] 10.305338                  2.966479
  [8,] 10.281051                  3.049590
  [9,] 10.227414                  3.082207
 [10,] 10.143964                  2.966479
 [11,] 10.019980                  3.130495
 [12,] 10.009995                  2.645751
 [13,]  9.974969                  2.966479
 [14,]  9.924717                  2.966479
 [15,]  9.899495                  3.098387
 [16,]  9.843780                  2.949576
 [17,]  9.803061                  2.449490
 [18,]  9.792855                  2.701851
 [19,]  9.721111                  2.774887
 [20,]  9.705668                  2.949576
 [21,]  9.695360                  2.880972
 [22,]  9.695360                  3.098387
 [23,]  9.695360                  3.000000
 [24,]  9.664368                  2.983287
 [25,]  9.581232                  2.408319
 [26,]  9.565563                  3.033150
 [27,]  9.560335                  2.863564
 [28,]  9.523655                  2.915476
 [29,]  9.513149                  2.549510
 [30,]  9.502631                  2.683282
 [31,]  9.481561                  2.983287
 [32,]  9.481561                  2.880972
 [33,]  9.428680                  2.898275
 [34,]  9.375500                  2.880972
 [35,]  9.370165                  2.846050
 [36,]  9.332738                  2.932576
 [37,]  9.327379                  2.932576
 [38,]  9.327379                  2.701851
 [39,]  9.322017                  3.049590
 [40,]  9.241212                  2.607681
 [41,]  9.230385                  2.774887
 [42,]  9.186947                  3.016621
 [43,]  9.121403                  3.098387
 [44,]  9.071935                  2.683282
 [45,]  9.066422                  2.863564
 [46,]  9.066422                  2.664583
 [47,]  9.060905                  2.720294
 [48,]  9.044335                  3.065942
 [49,]  9.038805                  3.098387
 [50,]  9.033272                  2.588436
 [51,]  9.022195                  2.898275
 [52,]  9.011104                  2.121320
 [53,]  8.983318                  2.190890
 [54,]  8.961027                  2.529822
 [55,]  8.955445                  2.846050
 [56,]  8.921883                  2.664583
 [57,]  8.921883                  2.626785
 [58,]  8.893818                  2.949576
 [59,]  8.837420                  2.792848
 [60,]  8.837420                  2.720294
 [61,]  8.820431                  2.810694
 [62,]  8.814760                  2.236068
 [63,]  8.803408                  2.949576
 [64,]  8.792042                  2.664583
 [65,]  8.752143                  2.932576
 [66,]  8.734987                  2.932576
 [67,]  8.723531                  2.863564
 [68,]  8.700575                  2.509980
 [69,]  8.694826                  2.387467
 [70,]  8.642916                  2.529822
 [71,]  8.631338                  2.949576
 [72,]  8.613942                  2.645751
 [73,]  8.608136                  2.915476
 [74,]  8.561542                  2.828427
 [75,]  8.549854                  2.756810
 [76,]  8.526429                  1.949359
 [77,]  8.502941                  2.469818
 [78,]  8.485281                  2.828427
 [79,]  8.479387                  2.167948
 [80,]  8.455767                  2.720294
 [81,]  8.408329                  2.626785
 [82,]  8.378544                  2.144761
 [83,]  8.366600                  2.236068
 [84,]  8.360622                  2.190890
 [85,]  8.354639                  2.626785
 [86,]  8.348653                  2.626785
 [87,]  8.330666                  2.588436
 [88,]  8.324662                  2.408319
 [89,]  8.324662                  2.607681
 [90,]  8.258329                  2.097618
 [91,]  8.246211                  2.469818
 [92,]  8.240146                  2.024846
 [93,]  8.215838                  1.949359
 [94,]  8.209750                  2.323790
 [95,]  8.173127                  2.073644
 [96,]  8.148620                  2.323790
 [97,]  8.148620                  2.073644
 [98,]  8.099383                  2.645751
 [99,]  8.093207                  2.588436
[100,]  8.080842                  2.073644
[101,]  8.068457                  2.167948
[102,]  8.068457                  2.024846
[103,]  8.068457                  2.549510
[104,]  8.031189                  2.366432
[105,]  7.981228                  2.387467
[106,]  7.930952                  2.280351
[107,]  7.893035                  2.720294
[108,]  7.867655                  2.190890
[109,]  7.848567                  2.408319
[110,]  7.797435                  2.529822
[111,]  7.784600                  2.024846
[112,]  7.765307                  2.846050
[113,]  7.765307                  2.049390
[114,]  7.752419                  2.489980
[115,]  7.733046                  2.236068
[116,]  7.726578                  2.345208
[117,]  7.713624                  2.428992
[118,]  7.635444                  2.097618
[119,]  7.615773                  2.024846
[120,]  7.549834                  1.843909
[121,]  7.536577                  2.024846
[122,]  7.436397                  2.792848
[123,]  7.422937                  2.024846
[124,]  7.416198                  2.258318
[125,]  7.395945                  1.673320
[126,]  7.334848                  1.923538
[127,]  7.328028                  2.024846
[128,]  7.300685                  2.049390
[129,]  7.280110                  2.121320
[130,]  7.273239                  2.024846
[131,]  7.197222                  2.323790
[132,]  7.162402                  2.190890
[133,]  7.155418                  2.097618
[134,]  7.014271                  2.509980
[135,]  6.985700                  1.870829
[136,]  6.978539                  2.213594
[137,]  6.978539                  2.049390
[138,]  6.978539                  2.190890
[139,]  6.811755                  2.387467
[140,]  6.737952                  1.923538
[141,]  6.730527                  2.280351
[142,]  6.723095                  1.949359
[143,]  6.640783                  2.190890
[144,]  6.595453                  1.816590
[145,]  6.580274                  1.788854
[146,]  6.526868                  2.144761
[147,]  6.496153                  2.428992
[148,]  6.473021                  1.843909
[149,]  6.363961                  1.732051
[150,]  6.356099                  1.702939
[151,]  6.340347                  1.788854
[152,]  6.276942                  1.897367
[153,]  6.212890                  1.702939
[154,]  6.164414                  1.760682
[155,]  6.148170                  1.612452
[156,]  6.082763                  1.897367
[157,]  5.865151                  1.843909
[158,]  5.744563                  1.923538
[159,]  5.612486                  1.581139
[160,]  5.603570                  2.049390
[161,]  5.522681                  2.428992
[162,]  5.366563                  1.760682
[163,]  5.224940                  1.897367
[164,]  5.069517                  2.000000
[165,]  5.049752                  1.581139
[166,]  4.959839                  1.516575
[167,]  4.939636                  1.897367
[168,]  4.690416                  1.949359
[169,]  4.582576                  1.581139
[170,]  4.538722                  1.732051
[171,]  4.415880                  1.549193
[172,]  4.415880                  1.673320
[173,]  4.347413                  1.095445
[174,]  4.230839                  1.516575
[175,]  4.219005                  1.549193
[176,]  4.086563                  1.048809
[177,]  4.000000                  1.303840
[178,]  3.962323                  1.224745
[179,]  3.807887                  1.183216

In [ ]:
class(sapply(fragility23[,4:5],sqrt))  # Check class, see if sapply simplified to matrix/array or kept as list

[1] "matrix" "array"

Now our own function:

In [ ]:
theOnesOK = function(DF_country_and_variable) {  # Custom function: takes data frame with country and variable columns
  variable_values <- DF_country_and_variable[,2]  # Extract second column (the variable values)
  avg_value <- mean(variable_values, na.rm = TRUE)  # Calculate average, ignoring missing values (na.rm removes NAs)
  is_above <- ifelse(variable_values > avg_value, "Above Average", "Below/At Average")  # Label each value as above or below average (ifelse works on vectors)
  DF_country_and_variable$Status <- is_above  # Add new Status column to data frame
  return(DF_country_and_variable)  # Return modified data frame with Status column
}

In [ ]:
theOnesOK(fragility23[,c('Country','S1: Demographic Pressures')])  # Call function with Country and Demographic Pressures columns, adds Status column

    Country                   S1: Demographic Pressures Status
1   Somalia                   10.0                      Above Average
2   Yemen                      9.6                      Above Average
3   South Sudan                9.7                      Above Average
4   Congo Democratic Republic  9.7                      Above Average
5   Syria                      7.4                      Above Average
6   Afghanistan                9.2                      Above Average
7   Sudan                      8.8                      Above Average
8   Central African Republic   9.3                      Above Average
9   Chad                       9.5                      Above Average
10  Haiti                      8.8                      Above Average
11  Ethiopia                   9.8                      Above Average
12  Myanmar                    7.0                      Above Average
13  Mali                       8.8                      Above Average
14  Guinea                     8.8                      Above Average
15  Nigeria                    9.6                      Above Average
16  Zimbabwe                   8.7                      Above Average
17  Libya                      6.0                      Above Average
18  Ukraine                    7.3                      Above Average
19  Eritrea                    7.7                      Above Average
20  Burundi                    8.7                      Above Average
21  Burkina Faso               8.3                      Above Average
22  Mozambique                 9.6                      Above Average
23  Cameroon                   9.0                      Above Average
24  Niger                      8.9                      Above Average
25  Lebanon                    5.8                      Below/At Average
26  Uganda                     9.2                      Above Average
27  Iraq                       8.2                      Above Average
28  Congo Republic             8.5                      Above Average
29  Venezuela                  6.5                      Above Average
30  Sri Lanka                  7.2                      Above Average
⋮   ⋮                         ⋮                         ⋮
150 Costa Rica                2.9                       Below/At Average
151 Czech Republic            3.2                       Below/At Average
152 Lithuania                 3.6                       Below/At Average
153 Estonia                   2.9                       Below/At Average
154 Mauritius                 3.1                       Below/At Average
155 Slovak Republic           2.6                       Below/At Average
156 United Arab Emirates      3.6                       Below/At Average
157 Uruguay                   3.4                       Below/At Average
158 Malta                     3.7                       Below/At Average
159 South Korea               2.5                       Below/At Average
160 Belgium                   4.2                       Below/At Average
161 Japan                     5.9                       Below/At Average
162 France                    3.1                       Below/At Average
163 Slovenia                  3.6                       Below/At Average
164 Portugal                  4.0                       Below/At Average
165 Singapore                 2.5                       Below/At Average
166 Germany                   2.3                       Below/At Average
167 Austria                   3.6                       Below/At Average
168 Australia                 3.8                       Below/At Average
169 Netherlands               2.5                       Below/At Average
170 Sweden                    3.0                       Below/At Average
171 Luxembourg                2.4                       Below/At Average
172 Ireland                   2.8                       Below/At Average
173 Canada                    1.2                       Below/At Average
174 Denmark                   2.3                       Below/At Average
175 Switzerland               2.4                       Below/At Average
176 New Zealand               1.1                       Below/At Average
177 Finland                   1.7                       Below/At Average
178 Iceland                   1.5                       Below/At Average
179 Norway                    1.4                       Below/At Average

In [ ]:
theOnesOK2 = function(DF, DFvariable, CountryColumn='Country') {  # Improved function: takes data frame, variable column name, and optional country column name
  variable_values <- DF[,DFvariable]  # Extract the specified variable column (more flexible than assuming column 2)
  avg_value <- mean(variable_values, na.rm = TRUE)  # Calculate mean, ignoring missing values
  is_above <- ifelse(variable_values > avg_value, "Above Average", "Below/At Average")  # Label each value as above or below average
  newname = paste('Status_on', DFvariable)  # Create dynamic column name by combining 'Status_on' with variable name
  DF[,newname] <- is_above   # Add new column with dynamic name to data frame
  return(DF[,c(CountryColumn, newname)])  # Return only country column and new status column (cleaner output)
}

In [ ]:
theOnesOK2(fragility23, 'S1: Demographic Pressures')  # Call function with full data frame and variable column name (uses default 'Country' column name)

    Country                   Status_on S1: Demographic Pressures
1   Somalia                   Above Average
2   Yemen                     Above Average
3   South Sudan               Above Average
4   Congo Democratic Republic Above Average
5   Syria                     Above Average
6   Afghanistan               Above Average
7   Sudan                     Above Average
8   Central African Republic  Above Average
9   Chad                      Above Average
10  Haiti                     Above Average
11  Ethiopia                  Above Average
12  Myanmar                   Above Average
13  Mali                      Above Average
14  Guinea                    Above Average
15  Nigeria                   Above Average
16  Zimbabwe                  Above Average
17  Libya                     Above Average
18  Ukraine                   Above Average
19  Eritrea                   Above Average
20  Burundi                   Above Average
21  Burkina Faso              Above Average
22  Mozambique                Above Average
23  Cameroon                  Above Average
24  Niger                     Above Average
25  Lebanon                   Below/At Average
26  Uganda                    Above Average
27  Iraq                      Above Average
28  Congo Republic            Above Average
29  Venezuela                 Above Average
30  Sri Lanka                 Above Average
⋮   ⋮                         ⋮
150 Costa Rica                Below/At Average
151 Czech Republic            Below/At Average
152 Lithuania                 Below/At Average
153 Estonia                   Below/At Average
154 Mauritius                 Below/At Average
155 Slovak Republic           Below/At Average
156 United Arab Emirates      Below/At Average
157 Uruguay                   Below/At Average
158 Malta                     Below/At Average
159 South Korea               Below/At Average
160 Belgium                   Below/At Average
161 Japan                     Below/At Average
162 France                    Below/At Average
163 Slovenia                  Below/At Average
164 Portugal                  Below/At Average
165 Singapore                 Below/At Average
166 Germany                   Below/At Average
167 Austria                   Below/At Average
168 Australia                 Below/At Average
169 Netherlands               Below/At Average
170 Sweden                    Below/At Average
171 Luxembourg                Below/At Average
172 Ireland                   Below/At Average
173 Canada                    Below/At Average
174 Denmark                   Below/At Average
175 Switzerland               Below/At Average
176 New Zealand               Below/At Average
177 Finland                   Below/At Average
178 Iceland                   Below/At Average
179 Norway                    Below/At Average

In [ ]:
mystery=function(DF,positionsToUse,CountryColumn='Country'){  # Function calculates row averages across specified columns
  newDF=DF[,c(CountryColumn),drop = FALSE]  # Start with just country column (drop=FALSE keeps it as data frame)
  average='average'  # Name for the new average column
  newDF[,average]=apply(DF[,positionsToUse],1,mean,na.rm = TRUE)  # Calculate mean across specified columns for each row (1=rows, na.rm ignores missing values)
  return(newDF[,c(CountryColumn,average)])  # Return country column and new average column
}

In [ ]:
fragility23[,c('Total',	'S1: Demographic Pressures')]  # Display Total and Demographic Pressures columns (to see available columns)

    Total S1: Demographic Pressures
1   111.9 10.0
2   108.9  9.6
3   108.5  9.7
4   107.2  9.7
5   107.1  7.4
6   106.6  9.2
7   106.2  8.8
8   105.7  9.3
9   104.6  9.5
10  102.9  8.8
11  100.4  9.8
12  100.2  7.0
13   99.5  8.8
14   98.5  8.8
15   98.0  9.6
16   96.9  8.7
17   96.1  6.0
18   95.9  7.3
19   94.5  7.7
20   94.2  8.7
21   94.0  8.3
22   94.0  9.6
23   94.0  9.0
24   93.4  8.9
25   91.8  5.8
26   91.5  9.2
27   91.4  8.2
28   90.7  8.5
29   90.5  6.5
30   90.3  7.2
⋮   ⋮     ⋮
150 40.4  2.9
151 40.2  3.2
152 39.4  3.6
153 38.6  2.9
154 38.0  3.1
155 37.8  2.6
156 37.0  3.6
157 34.4  3.4
158 33.0  3.7
159 31.5  2.5
160 31.4  4.2
161 30.5  5.9
162 28.8  3.1
163 27.3  3.6
164 25.7  4.0
165 25.5  2.5
166 24.6  2.3
167 24.4  3.6
168 22.0  3.8
169 21.0  2.5
170 20.6  3.0
171 19.5  2.4
172 19.5  2.8
173 18.9  1.2
174 17.9  2.3
175 17.8  2.4
176 16.7  1.1
177 16.0  1.7
178 15.7  1.5
179 14.5  1.4

## Examining theOnesOK2 Function

**What it does:** The theOnesOK2 function looks at a numeric column in the data frame and labels each row as "Above Average" or "Below/At Average" based on whether the value is higher than the column's mean.

It takes the full data frame (`DF`), the name of the variable column we want to analyze as a string (`DFvariable`), and optionally which column has country names (`CountryColumn`, defaults to 'Country'). It extracts the `DFvariable` column, calculates the mean, compares each value to the mean using `ifelse()`, creates a status column with a dynamic name like `'Status_on S1: Demographic Pressures'` (combining 'Status_on' with the variable name), and returns just the country and status columns.

**How it differs from theOnesOK:**

- **Input:** `theOnesOK` needs a pre-subsetted data frame with exactly 2 columns, while `theOnesOK2` takes the full data frame and a column name string which is much more flexible.

- **Column selection:** `theOnesOK` assumes the variable is always in column 2, but `theOnesOK2` lets us pick any column by name.

- **Output:** `theOnesOK` returns the whole input data frame with a `Status` column added, while `theOnesOK2` returns only country and status(cleaner and more focused).

- **Column naming:** `theOnesOK` always names it `Status`, but `theOnesOK2` creates dynamic names like `Status_on S1: Demographic Pressures` (combining 'Status_on' with the variable name) so we know which variable it refers to.

- **Reusability:** `theOnesOK2` is more reusable: we can analyze different variables without creating new subsets each time, and it works with any country column name.

## Explaining the Mystery Function

**What it does:** The mystery function calculates the average (mean) across multiple specified columns for each row in a data frame, then returns a simplified data frame containing just the country names and these calculated row averages.

**Input:** The function takes three arguments. First, it requires the full data frame (`DF`) that contains the columns we want to analyze. Second, it needs a vector of column positions (`positionsToUse`) that specifies which columns should be included in the average calculation - we can provide any number of column positions in this vector. Third, it optionally accepts the name of the column that contains country identifiers (`CountryColumn`), which defaults to 'Country' if not specified.

**Process:** The function begins by creating a new data frame that contains only the country column from the original data frame, using `drop = FALSE` to ensure it remains as a data frame structure even if there's only one column. Then, it uses the `apply()` function with the argument `1` (which means "apply to each row") to calculate the mean across all the columns specified in `positionsToUse`. The `mean` function is applied with `na.rm = TRUE`, which means any missing values (NAs) in those columns are ignored during the calculation. This process results in one average value for each row. The function then adds this calculated average as a new column named 'average' to the data frame.

**Output:** The function returns a simplified data frame that contains only two columns: the country column and the newly created 'average' column. Each row in this output represents one country (or whatever identifier is in the country column), paired with its corresponding average value calculated across the specified columns.

**Key features:** The function is flexible - it works with any number of columns specified by their positions, handles missing values gracefully by ignoring them during calculation, and produces a clean, focused output with just the essential information. We can also customize which column serves as the country identifier if it's not named 'Country'.